# TensorFlow Basics

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
print(tf.__version__)

2.6.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess :

    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [25]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [26]:
# sess = tf.Session()
for op in my_ops:
    print(op.eval())
#     print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.19641925  0.43750477  0.01924498  0.36482692]
 [ 0.02206217  0.40723765 -0.68244547 -0.07353821]
 [-1.1576056  -0.5754806  -0.2303004   0.02073783]
 [ 0.29161018 -0.9254553  -0.16678098 -0.4632763 ]]


[[0.861719   0.10528564 0.30333054 0.3574686 ]
 [0.34849954 0.44296265 0.01354265 0.9897696 ]
 [0.34965587 0.01094115 0.6322988  0.85273206]
 [0.83415174 0.16297424 0.7286713  0.34125006]]




## Matrix Multiplication

In [27]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [28]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [29]:
b = tf.constant([[10],
                 [100]])

In [30]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [31]:
result = tf.matmul(a,b)

In [32]:
result.eval()

array([[210],
       [430]])